export const champions = [
  { id: 1, name: "Alistar", image: "/champions/alistar.avif" },
  { id: 2, name: "Annie", image: "/champions/annie.avif" },
  { id: 3, name: "Ashe", image: "/champions/ashe.avif" },
  { id: 4, name: "Fiddlesticks", image: "/champions/fiddlesticks.avif" },
  { id: 5, name: "Jax", image: "/champions/jax.avif" },
  { id: 6, name: "Kayle", image: "/champions/kayle.avif" },
  { id: 7, name: "Master Yi", image: "/champions/master yi.avif" },
  { id: 8, name: "Morgana", image: "/champions/morgana.avif" },
  { id: 9, name: "Nunu & Willump", image: "/champions/nunu & willump.avif" },
  { id: 10, name: "Ryze", image: "/champions/ryze.avif" },
  { id: 11, name: "Sion", image: "/champions/sion.avif" },
  { id: 12, name: "Sivir", image: "/champions/sivir.avif" },
  { id: 13, name: "Soraka", image: "/champions/soraka.avif" },
  { id: 14, name: "Teemo", image: "/champions/teemo.avif" },
  { id: 15, name: "Tristana", image: "/champions/tristana.avif" },
  { id: 16, name: "Twisted Fate", image: "/champions/twisted fate.avif" },
  { id: 17, name: "Warwick", image: "/champions/warwick.avif" },
  { id: 18, name: "Singed", image: "/champions/singed.avif" },
  { id: 19, name: "Zilean", image: "/champions/zilean.avif" },
  { id: 20, name: "Evelynn", image: "/champions/evelynn.avif" },
  { id: 21, name: "Tryndamere", image: "/champions/tryndamere.avif" },
  { id: 22, name: "Twitch", image: "/champions/twitch.avif" },
  { id: 23, name: "Karthus", image: "/champions/karthus.avif" },
  { id: 24, name: "Amumu", image: "/champions/amumu.avif" },
  { id: 25, name: "Cho'Gath", image: "/champions/cho'gath.avif" },
  { id: 26, name: "Anivia", image: "/champions/anivia.avif" },
  { id: 27, name: "Rammus", image: "/champions/rammus.avif" },
  { id: 28, name: "Veigar", image: "/champions/veigar.avif" },
  { id: 29, name: "Kassadin", image: "/champions/kassadin.avif" },
  { id: 30, name: "Gangplank", image: "/champions/gangplank.avif" },
  { id: 31, name: "Taric", image: "/champions/taric.avif" },
  { id: 32, name: "Blitzcrank", image: "/champions/blitzcrank.avif" },
  { id: 33, name: "Dr. Mundo", image: "/champions/dr mundo.avif" },
  { id: 34, name: "Janna", image: "/champions/janna.avif" },
  { id: 35, name: "Malphite", image: "/champions/malphite.avif" },
  { id: 36, name: "Corki", image: "/champions/corki.avif" },
  { id: 37, name: "Katarina", image: "/champions/katarina.avif" },
  { id: 38, name: "Nasus", image: "/champions/nasus.avif" },
  { id: 39, name: "Heimerdinger", image: "/champions/heimerdinger.avif" },
  { id: 40, name: "Shaco", image: "/champions/shaco.avif" },
  { id: 41, name: "Udyr", image: "/champions/udyr.avif" },
  { id: 42, name: "Nidalee", image: "/champions/nidalee.avif" },
  { id: 43, name: "Poppy", image: "/champions/poppy.avif" },
  { id: 44, name: "Gragas", image: "/champions/gragas.avif" },
  { id: 45, name: "Pantheon", image: "/champions/pantheon.avif" },
  { id: 46, name: "Mordekaiser", image: "/champions/mordekaiser.avif" },
  { id: 47, name: "Ezreal", image: "/champions/ezreal.avif" },
  { id: 48, name: "Shen", image: "/champions/shen.avif" },
  { id: 49, name: "Kennen", image: "/champions/kennen.avif" },
  { id: 50, name: "Garen", image: "/champions/garen.avif" },
  { id: 51, name: "Akali", image: "/champions/akali.avif" },
  { id: 52, name: "Malzahar", image: "/champions/malzahar.avif" },
  { id: 53, name: "Olaf", image: "/champions/olaf.avif" },
  { id: 54, name: "Kog'Maw", image: "/champions/kog'maw.avif" },
  { id: 55, name: "Xin Zhao", image: "/champions/xin zhao.avif" },
  { id: 56, name: "Vladimir", image: "/champions/vladimir.avif" },
  { id: 57, name: "Galio", image: "/champions/galio.avif" },
  { id: 58, name: "Urgot", image: "/champions/urgot.avif" },
  { id: 59, name: "Miss Fortune", image: "/champions/miss fortune.avif" },
  { id: 60, name: "Sona", image: "/champions/sona.avif" },
  { id: 61, name: "Swain", image: "/champions/swain.avif" },
  { id: 62, name: "Lux", image: "/champions/lux.avif" },
  { id: 63, name: "LeBlanc", image: "/champions/leblanc.avif" },
  { id: 64, name: "Irelia", image: "/champions/irelia.avif" },
  { id: 65, name: "Trundle", image: "/champions/trundle.avif" },
  { id: 66, name: "Cassiopeia", image: "/champions/cassiopeia.avif" },
  { id: 67, name: "Caitlyn", image: "/champions/caitlyn.avif" },
  { id: 68, name: "Renekton", image: "/champions/renekton.avif" },
  { id: 69, name: "Karma", image: "/champions/karma.avif" },
  { id: 70, name: "Maokai", image: "/champions/maokai.avif" },
  { id: 71, name: "Jarvan IV", image: "/champions/jarvan iv.avif" },
  { id: 72, name: "Nocturne", image: "/champions/nocturne.avif" },
  { id: 73, name: "Lee Sin", image: "/champions/lee sin.avif" },
  { id: 74, name: "Brand", image: "/champions/brand.avif" },
  { id: 75, name: "Rumble", image: "/champions/rumble.avif" },
  { id: 76, name: "Vayne", image: "/champions/vayne.avif" },
  { id: 77, name: "Orianna", image: "/champions/orianna.avif" },
  { id: 78, name: "Yorick", image: "/champions/yorick.avif" },
  { id: 79, name: "Leona", image: "/champions/leona.avif" },
  { id: 80, name: "Wukong", image: "/champions/wukong.avif" },
  { id: 81, name: "Skarner", image: "/champions/skarner.avif" },
  { id: 82, name: "Talon", image: "/champions/talon.avif" },
  { id: 83, name: "Riven", image: "/champions/riven.avif" },
  { id: 84, name: "Xerath", image: "/champions/xerath.avif" },
  { id: 85, name: "Graves", image: "/champions/graves.avif" },
  { id: 86, name: "Shyvana", image: "/champions/shyvana.avif" },
  { id: 87, name: "Fizz", image: "/champions/fizz.avif" },
  { id: 88, name: "Volibear", image: "/champions/volibear.avif" },
  { id: 89, name: "Ahri", image: "/champions/ahri.avif" },
  { id: 90, name: "Viktor", image: "/champions/viktor.avif" },
  { id: 91, name: "Sejuani", image: "/champions/sejuani.avif" },
  { id: 92, name: "Ziggs", image: "/champions/ziggs.avif" },
  { id: 93, name: "Nautilus", image: "/champions/nautilus.avif" },
  { id: 94, name: "Fiora", image: "/champions/fiora.avif" },
  { id: 95, name: "Lulu", image: "/champions/lulu.avif" },
  { id: 96, name: "Hecarim", image: "/champions/hecarim.avif" },
  { id: 97, name: "Varus", image: "/champions/varus.avif" },
  { id: 98, name: "Darius", image: "/champions/darius.avif" },
  { id: 99, name: "Draven", image: "/champions/draven.avif" },
  { id: 100, name: "Jayce", image: "/champions/jayce.avif" },
  { id: 101, name: "Zyra", image: "/champions/zyra.avif" },
  { id: 102, name: "Diana", image: "/champions/diana.avif" },
  { id: 103, name: "Rengar", image: "/champions/rengar.avif" },
  { id: 104, name: "Syndra", image: "/champions/syndra.avif" },
  { id: 105, name: "Kha'Zix", image: "/champions/kha'zix.avif" },
  { id: 106, name: "Elise", image: "/champions/elise.avif" },
  { id: 107, name: "Zed", image: "/champions/zed.avif" },
  { id: 108, name: "Nami", image: "/champions/nami.avif" },
  { id: 109, name: "Vi", image: "/champions/vi.avif" },
  { id: 110, name: "Thresh", image: "/champions/thresh.avif" },
  { id: 111, name: "Quinn", image: "/champions/quinn.avif" },
  { id: 112, name: "Zac", image: "/champions/zac.avif" },
  { id: 113, name: "Lissandra", image: "/champions/lissandra.avif" },
  { id: 114, name: "Aatrox", image: "/champions/aatrox.avif" },
  { id: 115, name: "Lucian", image: "/champions/lucian.avif" },
  { id: 116, name: "Jinx", image: "/champions/jinx.avif" },
  { id: 117, name: "Yasuo", image: "/champions/yasuo.avif" },
  { id: 118, name: "Vel'Koz", image: "/champions/vel'koz.avif" },
  { id: 119, name: "Braum", image: "/champions/braum.avif" },
  { id: 120, name: "Gnar", image: "/champions/gnar.avif" },
  { id: 121, name: "Azir", image: "/champions/azir.avif" },
  { id: 122, name: "Kalista", image: "/champions/kalista.avif" },
  { id: 123, name: "Rek'Sai", image: "/champions/rek'sai.avif" },
  { id: 124, name: "Bard", image: "/champions/bard.avif" },
  { id: 125, name: "Ekko", image: "/champions/ekko.avif" },
  { id: 126, name: "Tahm Kench", image: "/champions/tahm kench.avif" },
  { id: 127, name: "Kindred", image: "/champions/kindred.avif" },
  { id: 128, name: "Illaoi", image: "/champions/illaoi.avif" },
  { id: 129, name: "Jhin", image: "/champions/jhin.avif" },
  { id: 130, name: "Aurelion Sol", image: "/champions/aurelion sol.avif" },
  { id: 131, name: "Taliyah", image: "/champions/taliyah.avif" },
  { id: 132, name: "Kled", image: "/champions/kled.avif" },
  { id: 133, name: "Ivern", image: "/champions/ivern.avif" },
  { id: 134, name: "Camille", image: "/champions/camille.avif" },
  { id: 135, name: "Rakan", image: "/champions/rakan.avif" },
  { id: 136, name: "Xayah", image: "/champions/xayah.avif" },
  { id: 137, name: "Kayn", image: "/champions/kayn.avif" },
  { id: 138, name: "Ornn", image: "/champions/ornn.avif" },
  { id: 139, name: "Zoe", image: "/champions/zoe.avif" },
  { id: 140, name: "Kai'Sa", image: "/champions/kai'sa.avif" },
  { id: 141, name: "Pyke", image: "/champions/pyke.avif" },
  { id: 142, name: "Neeko", image: "/champions/neeko.avif" },
  { id: 143, name: "Sylas", image: "/champions/sylas.avif" },
  { id: 144, name: "Yuumi", image: "/champions/yuumi.avif" },
  { id: 145, name: "Qiyana", image: "/champions/qiyana.avif" },
  { id: 146, name: "Senna", image: "/champions/senna.avif" },
  { id: 147, name: "Aphelios", image: "/champions/aphelios.jpg" },
  { id: 148, name: "Sett", image: "/champions/sett.jpg" },
  { id: 149, name: "Lillia", image: "/champions/lillia.jpg" },
  { id: 150, name: "Yone", image: "/champions/yone.jpg" },
  { id: 151, name: "Samira", image: "/champions/samira.jpg" },
  { id: 152, name: "Seraphine", image: "/champions/seraphine.jpg" },
  { id: 153, name: "Rell", image: "/champions/rell.avif" },
  { id: 154, name: "Viego", image: "/champions/viego.avif" },
  { id: 155, name: "Gwen", image: "/champions/gwen.avif" },
  { id: 156, name: "Akshan", image: "/champions/akshan.avif" },
  { id: 157, name: "Vex", image: "/champions/vex.avif" },
  { id: 158, name: "Zeri", image: "/champions/zeri.avif" },
  { id: 159, name: "Renata Glasc", image: "/champions/renata glasc.avif" },
  { id: 160, name: "Bel'Veth", image: "/champions/bel'veth.avif" },
  { id: 161, name: "Nilah", image: "/champions/nilah.avif" },
  { id: 162, name: "K'Sante", image: "/champions/k'sante.avif" },
  { id: 163, name: "Milio", image: "/champions/milio.avif" },
  { id: 164, name: "Naafiri", image: "/champions/naafiri.avif" },
  { id: 165, name: "Briar", image: "/champions/briar.avif" },
  { id: 166, name: "Hwei", image: "/champions/hwei.avif" },
  { id: 167, name: "Smolder", image: "/champions/smolder.avif" },
  { id: 168, name: "Aurora", image: "/champions/aurora.avif" },
  { id: 169, name: "Ambessa", image: "/champions/ambessa.avif" },
  { id: 170, name: "Mel", image: "/champions/mel.avif" },
  { id: 171, name: "Yunara", image: "/champions/yunara.avif" },
  { id: 172, name: "Zaahen", image: "/champions/zaahen.avif"  }
];

export const pickBanSequence = [
  { type: "ban", side: "B"}, // blue ban 1
  { type: "ban", side: "R"}, // red ban 1
  { type: "ban", side: "B"}, // blue ban 2
  { type: "ban", side: "R"}, // red ban 2
  { type: "ban", side: "B"}, // blue ban 3
  { type: "ban", side: "R"}, // red ban 3

  { type: "pick", side: "B"}, // B1
  { type: "pick", side: "R"}, // R1
  { type: "pick", side: "R"}, // R2
  { type: "pick", side: "B"}, // B2
  { type: "pick", side: "B"}, // B3
  { type: "pick", side: "R"}, // R3

  { type: "ban", side: "B"}, // blue ban 4
  { type: "ban", side: "R"}, // red ban 4
  { type: "ban", side: "B"}, // blue ban 5
  { type: "ban", side: "R"}, // red ban 5

  { type: "pick", side: "R"}, // R4
  { type: "pick", side: "B"}, // B4
  { type: "pick", side: "B"}, // B5
  { type: "pick", side: "R"} // R5
];
