export const champions = [
  { id: 1, name: "Alistar", image: "/champions/alistar.png" },
  { id: 2, name: "Annie", image: "/champions/annie.png" },
  { id: 3, name: "Ashe", image: "/champions/ashe.png" },
  { id: 4, name: "Fiddlesticks", image: "/champions/fiddlesticks.png" },
  { id: 5, name: "Jax", image: "/champions/jax.png" },
  { id: 6, name: "Kayle", image: "/champions/kayle.png" },
  { id: 7, name: "Master Yi", image: "/champions/masteryi.png" },
  { id: 8, name: "Morgana", image: "/champions/morgana.png" },
  { id: 9, name: "Nunu & Willump", image: "/champions/nunu.png" },
  { id: 10, name: "Ryze", image: "/champions/ryze.png" },
  { id: 11, name: "Sion", image: "/champions/sion.png" },
  { id: 12, name: "Sivir", image: "/champions/sivir.png" },
  { id: 13, name: "Soraka", image: "/champions/soraka.png" },
  { id: 14, name: "Teemo", image: "/champions/teemo.png" },
  { id: 15, name: "Tristana", image: "/champions/tristana.png" },
  { id: 16, name: "Twisted Fate", image: "/champions/twistedfate.png" },
  { id: 17, name: "Warwick", image: "/champions/warwick.png" },
  { id: 18, name: "Singed", image: "/champions/singed.png" },
  { id: 19, name: "Zilean", image: "/champions/zilean.png" },
  { id: 20, name: "Evelynn", image: "/champions/evelynn.png" },
  { id: 21, name: "Tryndamere", image: "/champions/tryndamere.png" },
  { id: 22, name: "Twitch", image: "/champions/twitch.png" },
  { id: 23, name: "Karthus", image: "/champions/karthus.png" },
  { id: 24, name: "Amumu", image: "/champions/amumu.png" },
  { id: 25, name: "Cho'Gath", image: "/champions/chogath.png" },
  { id: 26, name: "Anivia", image: "/champions/anivia.png" },
  { id: 27, name: "Rammus", image: "/champions/rammus.png" },
  { id: 28, name: "Veigar", image: "/champions/veigar.png" },
  { id: 29, name: "Kassadin", image: "/champions/kassadin.png" },
  { id: 30, name: "Gangplank", image: "/champions/gangplank.png" },
  { id: 31, name: "Taric", image: "/champions/taric.png" },
  { id: 32, name: "Blitzcrank", image: "/champions/blitzcrank.png" },
  { id: 33, name: "Dr. Mundo", image: "/champions/mundo.png" },
  { id: 34, name: "Janna", image: "/champions/janna.png" },
  { id: 35, name: "Malphite", image: "/champions/malphite.png" },
  { id: 36, name: "Corki", image: "/champions/corki.png" },
  { id: 37, name: "Katarina", image: "/champions/katarina.png" },
  { id: 38, name: "Nasus", image: "/champions/nasus.png" },
  { id: 39, name: "Heimerdinger", image: "/champions/heimerdinger.png" },
  { id: 40, name: "Shaco", image: "/champions/shaco.png" },
  { id: 41, name: "Udyr", image: "/champions/udyr.png" },
  { id: 42, name: "Nidalee", image: "/champions/nidalee.png" },
  { id: 43, name: "Poppy", image: "/champions/poppy.png" },
  { id: 44, name: "Gragas", image: "/champions/gragas.png" },
  { id: 45, name: "Pantheon", image: "/champions/pantheon.png" },
  { id: 46, name: "Mordekaiser", image: "/champions/mordekaiser.png" },
  { id: 47, name: "Ezreal", image: "/champions/ezreal.png" },
  { id: 48, name: "Shen", image: "/champions/shen.png" },
  { id: 49, name: "Kennen", image: "/champions/kennen.png" },
  { id: 50, name: "Garen", image: "/champions/garen.png" },
  { id: 51, name: "Akali", image: "/champions/akali.png" },
  { id: 52, name: "Malzahar", image: "/champions/malzahar.png" },
  { id: 53, name: "Olaf", image: "/champions/olaf.png" },
  { id: 54, name: "Kog'Maw", image: "/champions/kogmaw.png" },
  { id: 55, name: "Xin Zhao", image: "/champions/xinzhao.png" },
  { id: 56, name: "Vladimir", image: "/champions/vladimir.png" },
  { id: 57, name: "Galio", image: "/champions/galio.png" },
  { id: 58, name: "Urgot", image: "/champions/urgot.png" },
  { id: 59, name: "Miss Fortune", image: "/champions/missfortune.png" },
  { id: 60, name: "Sona", image: "/champions/sona.png" },
  { id: 61, name: "Swain", image: "/champions/swain.png" },
  { id: 62, name: "Lux", image: "/champions/lux.png" },
  { id: 63, name: "LeBlanc", image: "/champions/leblanc.png" },
  { id: 64, name: "Irelia", image: "/champions/irelia.png" },
  { id: 65, name: "Trundle", image: "/champions/trundle.png" },
  { id: 66, name: "Cassiopeia", image: "/champions/cassiopeia.png" },
  { id: 67, name: "Caitlyn", image: "/champions/caitlyn.png" },
  { id: 68, name: "Renekton", image: "/champions/renekton.png" },
  { id: 69, name: "Karma", image: "/champions/karma.png" },
  { id: 70, name: "Maokai", image: "/champions/maokai.png" },
  { id: 71, name: "Jarvan IV", image: "/champions/jarvan.png" },
  { id: 72, name: "Nocturne", image: "/champions/nocturne.png" },
  { id: 73, name: "Lee Sin", image: "/champions/leesin.png" },
  { id: 74, name: "Brand", image: "/champions/brand.png" },
  { id: 75, name: "Rumble", image: "/champions/rumble.png" },
  { id: 76, name: "Vayne", image: "/champions/vayne.png" },
  { id: 77, name: "Orianna", image: "/champions/orianna.png" },
  { id: 78, name: "Yorick", image: "/champions/yorick.png" },
  { id: 79, name: "Leona", image: "/champions/leona.png" },
  { id: 80, name: "Wukong", image: "/champions/wukong.png" },
  { id: 81, name: "Skarner", image: "/champions/skarner.png" },
  { id: 82, name: "Talon", image: "/champions/talon.png" },
  { id: 83, name: "Riven", image: "/champions/riven.png" },
  { id: 84, name: "Xerath", image: "/champions/xerath.png" },
  { id: 85, name: "Graves", image: "/champions/graves.png" },
  { id: 86, name: "Shyvana", image: "/champions/shyvana.png" },
  { id: 87, name: "Fizz", image: "/champions/fizz.png" },
  { id: 88, name: "Volibear", image: "/champions/volibear.png" },
  { id: 89, name: "Ahri", image: "/champions/ahri.png" },
  { id: 90, name: "Viktor", image: "/champions/viktor.png" },
  { id: 91, name: "Sejuani", image: "/champions/sejuani.png" },
  { id: 92, name: "Ziggs", image: "/champions/ziggs.png" },
  { id: 93, name: "Nautilus", image: "/champions/nautilus.png" },
  { id: 94, name: "Fiora", image: "/champions/fiora.png" },
  { id: 95, name: "Lulu", image: "/champions/lulu.png" },
  { id: 96, name: "Hecarim", image: "/champions/hecarim.png" },
  { id: 97, name: "Varus", image: "/champions/varus.png" },
  { id: 98, name: "Darius", image: "/champions/darius.png" },
  { id: 99, name: "Draven", image: "/champions/draven.png" },
  { id: 100, name: "Jayce", image: "/champions/jayce.png" },
  { id: 101, name: "Zyra", image: "/champions/zyra.png" },
  { id: 102, name: "Diana", image: "/champions/diana.png" },
  { id: 103, name: "Rengar", image: "/champions/rengar.png" },
  { id: 104, name: "Syndra", image: "/champions/syndra.png" },
  { id: 105, name: "Kha'Zix", image: "/champions/khazix.png" },
  { id: 106, name: "Elise", image: "/champions/elise.png" },
  { id: 107, name: "Zed", image: "/champions/zed.png" },
  { id: 108, name: "Nami", image: "/champions/nami.png" },
  { id: 109, name: "Vi", image: "/champions/vi.png" },
  { id: 110, name: "Thresh", image: "/champions/thresh.png" },
  { id: 111, name: "Quinn", image: "/champions/quinn.png" },
  { id: 112, name: "Zac", image: "/champions/zac.png" },
  { id: 113, name: "Lissandra", image: "/champions/lissandra.png" },
  { id: 114, name: "Aatrox", image: "/champions/aatrox.png" },
  { id: 115, name: "Lucian", image: "/champions/lucian.png" },
  { id: 116, name: "Jinx", image: "/champions/jinx.png" },
  { id: 117, name: "Yasuo", image: "/champions/yasuo.png" },
  { id: 118, name: "Vel'Koz", image: "/champions/velkoz.png" },
  { id: 119, name: "Braum", image: "/champions/braum.png" },
  { id: 120, name: "Gnar", image: "/champions/gnar.png" },
  { id: 121, name: "Azir", image: "/champions/azir.png" },
  { id: 122, name: "Kalista", image: "/champions/kalista.png" },
  { id: 123, name: "Rek'Sai", image: "/champions/reksai.png" },
  { id: 124, name: "Bard", image: "/champions/bard.png" },
  { id: 125, name: "Ekko", image: "/champions/ekko.png" },
  { id: 126, name: "Tahm Kench", image: "/champions/tahmkench.png" },
  { id: 127, name: "Kindred", image: "/champions/kindred.png" },
  { id: 128, name: "Illaoi", image: "/champions/illaoi.png" },
  { id: 129, name: "Jhin", image: "/champions/jhin.png" },
  { id: 130, name: "Aurelion Sol", image: "/champions/aurelion.png" },
  { id: 131, name: "Taliyah", image: "/champions/taliyah.png" },
  { id: 132, name: "Kled", image: "/champions/kled.png" },
  { id: 133, name: "Ivern", image: "/champions/ivern.png" },
  { id: 134, name: "Camille", image: "/champions/camille.png" },
  { id: 135, name: "Rakan", image: "/champions/rakan.png" },
  { id: 136, name: "Xayah", image: "/champions/xayah.png" },
  { id: 137, name: "Kayn", image: "/champions/kayn.png" },
  { id: 138, name: "Ornn", image: "/champions/ornn.png" },
  { id: 139, name: "Zoe", image: "/champions/zoe.png" },
  { id: 140, name: "Kai'Sa", image: "/champions/kaisa.png" },
  { id: 141, name: "Pyke", image: "/champions/pyke.png" },
  { id: 142, name: "Neeko", image: "/champions/neeko.png" },
  { id: 143, name: "Sylas", image: "/champions/sylas.png" },
  { id: 144, name: "Yuumi", image: "/champions/yuumi.png" },
  { id: 145, name: "Qiyana", image: "/champions/qiyana.png" },
  { id: 146, name: "Senna", image: "/champions/senna.png" },
  { id: 147, name: "Aphelios", image: "/champions/aphelios.png" },
  { id: 148, name: "Sett", image: "/champions/sett.png" },
  { id: 149, name: "Lillia", image: "/champions/lillia.png" },
  { id: 150, name: "Yone", image: "/champions/yone.png" },
  { id: 151, name: "Samira", image: "/champions/samira.png" },
  { id: 152, name: "Seraphine", image: "/champions/seraphine.png" },
  { id: 153, name: "Rell", image: "/champions/rell.png" },
  { id: 154, name: "Viego", image: "/champions/viego.png" },
  { id: 155, name: "Gwen", image: "/champions/gwen.png" },
  { id: 156, name: "Akshan", image: "/champions/akshan.png" },
  { id: 157, name: "Vex", image: "/champions/vex.png" },
  { id: 158, name: "Zeri", image: "/champions/zeri.png" },
  { id: 159, name: "Renata Glasc", image: "/champions/renata.png" },
  { id: 160, name: "Bel'Veth", image: "/champions/belveth.png" },
  { id: 161, name: "Nilah", image: "/champions/nilah.png" },
  { id: 162, name: "K'Sante", image: "/champions/ksante.png" },
  { id: 163, name: "Milio", image: "/champions/milio.png" },
  { id: 164, name: "Naafiri", image: "/champions/naafiri.png" },
  { id: 165, name: "Briar", image: "/champions/briar.png" },
  { id: 166, name: "Hwei", image: "/champions/hwei.png" },
  { id: 167, name: "Smolder", image: "/champions/smolder.png" },
  { id: 168, name: "Aurora", image: "/champions/aurora.png" },
  { id: 169, name: "Ambessa", image: "/champions/ambessa.png" },
  { id: 170, name: "Mel", image: "/champions/mel.png" },
  { id: 171, name: "Yunara", image: "/champions/yunara.png" },
  { id: 172, name: "Zaahen", image: "/champions/zaahen.png"  }
];

export const pickBanSequence = [
  { type: "ban", side: "B"}, // blue ban 1
  { type: "ban", side: "R"}, // red ban 1
  { type: "ban", side: "B"}, // blue ban 2
  { type: "ban", side: "R"}, // red ban 2
  { type: "ban", side: "B"}, // blue ban 3
  { type: "ban", side: "R"}, // red ban 3

  { type: "pick", side: "B"}, // B1
  { type: "pick", side: "R"}, // R1
  { type: "pick", side: "R"}, // R2
  { type: "pick", side: "B"}, // B2
  { type: "pick", side: "B"}, // B3
  { type: "pick", side: "R"}, // R3

  { type: "ban", side: "B"}, // blue ban 4
  { type: "ban", side: "R"}, // red ban 4
  { type: "ban", side: "B"}, // blue ban 5
  { type: "ban", side: "R"}, // red ban 5

  { type: "pick", side: "R"}, // R4
  { type: "pick", side: "B"}, // B4
  { type: "pick", side: "B"}, // B5
  { type: "pick", side: "R"} // R5
];
